### ISSUE TITLE
Modpack Crashs on Pojavlauncher

### ISSUE THREAD

**Issue by Keno3704** [Permdog99/Legacy-Remade#3]
I've been trying to play this mod on my phone for a long time, but every time I try to use it it crashes right when I start it. Please convert this, it's my dream to play this on my phone.

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-08-12 22:12:14
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.NativeLibrary
	at dev.isxander.sdl3java.jna.SdlNativeLibraryLoader.loadLibSDL3FromFilePathNow(SdlNativeLibraryLoader.java:34)
	at wily.legacy.client.controller.SDLControllerHandler.init(SDLControllerHandler.java:92)
	at wily.legacy.client.controller.SDLControllerHandler.lambda$init$0(SDLControllerHandler.java:75)
	at MC//net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162)
	at MC//net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
	at MC//net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136)
	at MC//net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1240)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native [in thread "Render thread"]
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:90)
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67)
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18)
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41)
	at MC//net.minecraft.client.util.NarratorManager.<init>(NarratorManager.java:19)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:675)
	at net.minecraft.client.main.Main.main(Main.java:239)
	... 3 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.isxander.sdl3java.jna.SdlNativeLibraryLoader.loadLibSDL3FromFilePathNow(SdlNativeLibraryLoader.java:34)
	at wily.legacy.client.controller.SDLControllerHandler.init(SDLControllerHandler.java:92)
	at wily.legacy.client.controller.SDLControllerHandler.lambda$init$0(SDLControllerHandler.java:75)
	at MC//net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162)
	at MC//net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
	at MC//net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136)

-- Uptime --
Details:
	JVM uptime: 207.243s
	Wall uptime: 111.987s
	High-res time: 91.929s
	Client ticks: 1233 ticks / 61.650s
Stacktrace:
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2501)
	at MC//net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:949)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, balm-fabric, betterpingdisplay, bobby, caffeineconfig, clientsidenoteblocks, cloth-config, craftpresence, craterlib, debugify, defaultoptions, dynamic_fps, emojitype, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, forgeconfigapiport, fsb-interop, globalpacks, immediatelyfast, indium, infinite-music, krypton, legacy, lithium, modern_beta, modernfix, modmenu, netherportalfix, nochatreports, noisium, norecipebook, nvidium, old_combat_mod, oldmclogo, patched, polytone, preferred-gamerules, reeses-sodium-options, resourcepackoverrides, sodium, sodium-extra, sspb, stackdeobfuscator, stackdeobfuscator-common, ukulib, world-host, yet_another_config_lib_v3, Legacy Remade Resources

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (aarch64) version Android-9
	Java Version: 21.0.1-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 472320208 bytes (450 MiB) / 1098907648 bytes (1048 MiB) up to 1098907648 bytes (1048 MiB)
	CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 4016.09, total: 49486.64
	Space in storage for workdir (MiB): available: 4016.09, total: 49486.64
	JVM Flags: 3 total; -Xms1048M -Xmx1048M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Fabric Mods: 
		architectury: Architectury 13.0.3
		ash_api: Ash API 21.0.1-beta
		balm-fabric: Balm 21.0.12
			kuma_api: KumaAPI 21.0.4
		betterpingdisplay: Better Ping Display 1.1.1
		bobby: Bobby 5.2.3+mc1.21
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		chatsigninghider: Chat Signing Hider 1.21-1.0.5
		clientsidenoteblocks: ClientSideNoteblocks 2.8
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.70
		craftpresence: CraftPresence 2.4.3
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
		craterlib: CraterLib 2.0.1
		debugify: Debugify 1.21+1.0
		defaultoptions: Default Options 21.0.5
		dynamic_fps: Dynamic FPS 3.6.0
			net_lostluma_battery: battery 1.0.1
		emojitype: Emoji Type 2.2.5+1.21
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.100.6+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.17+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.1+86024ea6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.11+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.12+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.0+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.24+6ced4dd9d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.81+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		ferritecore: FerriteCore 7.0.0
		forgeconfigapiport: Forge Config API Port 21.0.1
			com_electronwill_night-config_core: core 3.7.4
			com_electronwill_night-config_toml: toml 3.7.4
		fsb-interop: FabricSkyBoxes Interop 1.4.0+mc1.21-build.54
		globalpacks: Global Data- & Resourcepacks 21.0.0
		hideexperimentalwarning: Hide Experimental Warning 1.1
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.34+mc1.21
		infinite-music: Infinite Music 0.4.3
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		legacy: Legacy4J 1.7.2
			dev_isxander_libsdl4j: libsdl4j 3.693c75e-36
		letmedespawn: Let Me Despawn 1.3.0
		lithium: Lithium 0.12.7
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modern_beta: Moderner Beta Fabric 6.5+er1.3.1+1.21
		modernfix: ModernFix 5.18.7+mc1.21
		modmenu: Mod Menu 11.0.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		netherportalfix: NetherPortalFix 21.0.2
		nochatreports: No Chat Reports 1.21-v2.8.0
		noisium: Noisium 2.2.1+mc1.21
		norecipebook: NoRecipeBook 3.3+1.21
		nvidium: Nvidium 0.2.9-beta
		old_combat_mod: Old Combat Mod 1.1.1
		olderskins: OlderSkins 1.0.0
		oldmclogo: Old MC Logo 1.1.3
		patched: Patched 7.0.0+1.21
		polytone: Polytone 1.21-2.1.1
			net_objecthunter_exp4j: exp4j 0.4.8
		preferred-gamerules: Preferred Gamerules 1.1.0+1.19.4
		puzzleslib: Puzzles Lib 21.0.12
		railoptimization: RailOptimization 1.2
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		resourcepackoverrides: Resource Pack Overrides 21.0.0
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sspb: Sodium Shadowy Path Blocks 3.3.0
		stackdeobfuscator: StackDeobfuscator 1.4.3+08e71cc
			net_fabricmc_mapping-io: mapping-io 0.6.1
			stackdeobfuscator-common: StackDeobfuscator Common 1.4.3+08e71cc
		ukulib: ukulib 1.4.0+1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		world-host: World Host 0.4.14+1.21-fabric
			org_quiltmc_parsers_json: json 0.3.0
			org_semver4j_semver4j: semver4j 5.3.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
	Launched Version: 1.21
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Adreno (TM) 509 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
	Window size: 1512x756
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, balm-fabric, betterpingdisplay, bobby, caffeineconfig, clientsidenoteblocks, cloth-config, craftpresence, craterlib, debugify, defaultoptions, dynamic_fps, emojitype, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, forgeconfigapiport, fsb-interop, globalpacks, immediatelyfast, indium, infinite-music, krypton, legacy, lithium, modern_beta, modernfix, modmenu, netherportalfix, nochatreports, noisium, norecipebook, nvidium, old_combat_mod, oldmclogo, patched, polytone, preferred-gamerules, reeses-sodium-options, resourcepackoverrides, sodium, sodium-extra, sspb, stackdeobfuscator, stackdeobfuscator-common, ukulib, world-host, yet_another_config_lib_v3, Legacy Remade Resources
	Current Language: en_us
	Locale: pt
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>

**Comment by Permdog99** [comment]
Please do not make duplicate issues. This is a problem with Legacy4J, please report it to them.
